version: '3.11'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=dasha
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=test_db

  nginx:
    image: nginx:latest
    depends_on:
      - django
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80


volumes:
  postgres_data: